name: Daily Script Run

on:
  schedule:
    - cron: '0 10 * * *'  # Runs at 10:00 AM UTC daily
  workflow_dispatch:      # Allows manual trigger too

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run script
        run: python script.py
